---
title: "about me"
subtitle: "Grayson's data science portfolio"
# use quarto markdown to 
---

# Grayson and Data

From time to time, there are individuals who seem to be born with code scrolling past the inner surface of their eyelids... This about me page is not about those individuals. I did not come from a heavy programming or statistical background. The majority of my undergraduate education focused on soft skills. I am interdisciplinarian with a focus on entrepreneurship within the Family and Consumer sciences. I obtained a minor in World Languages by learning Spanish and Portuguese, living for 7 months in Rio de Janeiro, Brazil. I have a passion for innovation and and changing the world through sharing good ideas. Good data fues good ideas, and developed hard skills give backbone to developed soft skills.I started looking for a skill set to compliment the creative and communicative skills I had been working on. Not knowing what data science really was, I began to take a few courses... and *slowly* I fell in love with the tools that could hlep me problem solve and communicate in ways I never could have before. I began to learn a little about the world of programming, and, though it was humbling, it was also empowering. So here I am - Grayson Johnson: entrepreneur, communicator, amateur data scientist.

