---
layout: cv
title: Grayson Johnson's CV
---
# Grayson Johnson
Interdisciplinarian, Entrepreneur, Firefighter, EMT.

<div id="webaddress">
<a href="https://www.linkedin.com/in/grayson-johnson-874043244/">LinkedIn</a>
| <a href="https://graysondjohnson.weebly.com/">My design portfolio</a>
</div>


## Currently

Owner of a startup

### Studying

Entrepreneurship and Innovation in Business - especially in apparel and design


### Research interests

Data science, innovation, leadership, communication, design

### Langauages

- English
- Spanish
- Portuguese


## Education

`2015 - 2019`
__Highland Senior High School, Pocatello, ID__

`September 2021 - July 2025`
__BYU-Idaho, Rexburg, ID__

- Bachelor in Interdisciplinary Studies with concentration in Family Consumer Science Entrepreneurship
- Minor in World Languages 
    - Portuguese, Spanish
- Certificate in Data Science


## Volunteer Experience
`September 2022 - January 2023`
__All In Sports Hoop.Camp__
Sponsorship Intern 

- Generated sponsorships and donations for an international nonprofit organization from universities and companies in a sales environment
- Responsibility for follow-up and accounts generated

`2019 - 2021`
__The Church of Jesus Christ of Latter Day Saints__
Full-Time Missionary 

- Connected with individuals and families of diverse cultures, races, backgrounds, and ages
- Coordinated training and communication with three teams of over twenty missionaries



## Work Experience

`June 2019 - present`
__Teton County Fire and Rescue__, Driggs, ID

- Wildland Firefighter and Hazaardous Fuels Crew
- Reserve Structre Firefighter and EMT

`January 2025 - July 2025`
__Integrated Business Core (IBC)__, BYU-Idaho

- Audit and Finance TA
- Lead TA
    - Led a team of 9 TA's
    - Coordinated with faculty and students
    - Planned, ran, and supported large scale and complex student events 
    - Generated and update meaningful charts and reports in R

`July 2025 - Present`
__Rocky Mountain Surf Project (Startup)__

- Founder and sole proprietor
- Regular manage inventory
- Create and execute marketing plans involving social media
- Product design and research
- Organize and lead focus groups
- Perfrom weekly financial analysis
- Generate meaningful charts and visualizations in R for research and marketing purposes

<!-- ### Footer

Last updated: May 2013 -->